/*

 CURSORS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Cursors[] =
{
  0xE0,0xE0,0x78,0x78,0x1E,0x1E,0x0F,0x0F,
  0x0F,0x0F,0x1E,0x1E,0x78,0x78,0xE0,0xE0
};

/* End of CURSORS.C */
